using System;
using System.Collections.Generic;
using System.Text;
using System.Collections;

namespace Simple_Bible_Reader
{
    public class ChapterHeadingUtil
    {
        static Hashtable map = null;

        public static string getChapterTitle(int book,int chapter)
        {
            if (map == null)
            {
                map = new Hashtable();

                // titles taken from bibleocity.com licensed under CC BY-NC-SA 4.0
                // few apocrypha headings from biblegateway.com

                // Genesis
                map.Add("1.1", "1. Creation & Recreation");
                map.Add("1.2", "2. Creation & Recreation Recap");
                map.Add("1.3", "3. The Fall of Man");
                map.Add("1.4", "4. Cain Murders Abel");
                map.Add("1.5", "5. Genealogies");
                map.Add("1.6", "6. The Flood");
                map.Add("1.7", "7. The Flood");
                map.Add("1.8", "8. The Flood");
                map.Add("1.9", "9. The Rainbow & Capital Punishment");
                map.Add("1.10", "10. Genealogies");
                map.Add("1.11", "11. The Tower of Babel");
                map.Add("1.12", "12. The Call of Abraham");
                map.Add("1.13", "13. The Cowboy Conflict");
                map.Add("1.14", "14. The Kidnapping of Lot");
                map.Add("1.15", "15. Abraham Believed God");
                map.Add("1.16", "16. Ishmael is Born");
                map.Add("1.17", "17. Abram becomes Abraham");
                map.Add("1.18", "18. Abraham prays for Sodom");
                map.Add("1.19", "19. Sodom is destroyed");
                map.Add("1.20", "20. Abraham lies about Serah at Gerar");
                map.Add("1.21", "21. The Birth of Isaac");
                map.Add("1.22", "22. The Offering of Isaac");
                map.Add("1.23", "23. The Death of Sarah");
                map.Add("1.24", "24. The Bride for Isaac");
                map.Add("1.25", "25. The Death of Abraham");
                map.Add("1.26", "26. Abrahamic Covenant Confirmed to Isaac");
                map.Add("1.27", "27. Jacob-Esau Birthright Conflict");
                map.Add("1.28", "28. Abrahamic Covenant Confirmed to Jacob");
                map.Add("1.29", "29. Jacob Marries Leah & Rachel");
                map.Add("1.30", "30. Jacob's Cattle (method of breeding)");
                map.Add("1.31", "31. Jacob Leaves Laban");
                map.Add("1.32", "32. Jacob Becomes Israel");
                map.Add("1.33", "33. Jacob's Reunion with Esau");
                map.Add("1.34", "34. The Distress of Dinah");
                map.Add("1.35", "35. Rachel Dies, Isaac Dies");
                map.Add("1.36", "36. The Generations of Esau");
                map.Add("1.37", "37. Joseph's Dream, Sold to Egypt");
                map.Add("1.38", "38. The Shame of Judah");
                map.Add("1.39", "39. Joseph, Potiphar, & Prison");
                map.Add("1.40", "40. Joseph's Butler-Baker Dream");
                map.Add("1.41", "41. Joseph, Minister of Agriculture");
                map.Add("1.42", "42. Joseph's 10 Brothers to Egypt to buy corn");
                map.Add("1.43", "43. Joseph's 11 Brothers to Egypt to buy corn");
                map.Add("1.44", "44. Benjamin's Silver Cup");
                map.Add("1.45", "45. Joseph Reveals All");
                map.Add("1.46", "46. Jacob and family move to Egypt");
                map.Add("1.47", "47. Joseph sells corn for land for Pharaoh");
                map.Add("1.48", "48. Joseph's Sons, Double Portion");
                map.Add("1.49", "49. Jacob's Evaluation of His Sons");
                map.Add("1.50", "50. Bones of Joseph (Jacob & Joseph Die)");
                map.Add("2.1", "1. Slavery in Egypt");
                map.Add("2.2", "2. The Birth of Moses");
                map.Add("2.3", "3. The Burning Bush");
                map.Add("2.4", "4. The Objections of Moses");
                map.Add("2.5", "5. Increased Slavery");
                map.Add("2.6", "6. Affirmation of Abrahamic Covenant");
                map.Add("2.7", "7-12. The Ten Plagues");
                map.Add("2.8", "7-12. The Ten Plagues");
                map.Add("2.9", "7-12. The Ten Plagues");
                map.Add("2.10", "7-12. The Ten Plagues");
                map.Add("2.11", "7-12. The Ten Plagues");
                map.Add("2.12", "7-12. The Ten Plagues");
                map.Add("2.13", "13. Guidance by Pillar of Cloud & Fire");
                map.Add("2.14", "14. Crossing of the Red Sea");
                map.Add("2.15", "15. Wrong Kind of Water (Marah)");
                map.Add("2.16", "16. Provision of Manna");
                map.Add("2.17", "17. No Water Situation (Rephidim)");
                map.Add("2.18", "18. Organization Man Jethro");
                map.Add("2.19", "19. Arrival at Mt. Sinai");
                map.Add("2.20", "20-31.Giving of Mosaic Law");
                map.Add("2.21", "20-31.Giving of Mosaic Law");
                map.Add("2.22", "20-31.Giving of Mosaic Law");
                map.Add("2.23", "20-31.Giving of Mosaic Law");
                map.Add("2.24", "20-31.Giving of Mosaic Law");
                map.Add("2.25", "20-31.Giving of Mosaic Law");
                map.Add("2.26", "20-31.Giving of Mosaic Law");
                map.Add("2.27", "20-31.Giving of Mosaic Law");
                map.Add("2.28", "20-31.Giving of Mosaic Law");
                map.Add("2.29", "20-31.Giving of Mosaic Law");
                map.Add("2.30", "20-31.Giving of Mosaic Law");
                map.Add("2.31", "20-31.Giving of Mosaic Law");
                map.Add("2.32", "32. Golden Calf (Stone tablets broken)");
                map.Add("2.33", "33. On to Canaan (Moses sees God)");
                map.Add("2.34", "34. Second Tablets of Stone");
                map.Add("2.35", "35-39. Tabernacle Parts Constructed");
                map.Add("2.36", "35-39. Tabernacle Parts Constructed");
                map.Add("2.37", "35-39. Tabernacle Parts Constructed");
                map.Add("2.38", "35-39. Tabernacle Parts Constructed");
                map.Add("2.39", "35-39. Tabernacle Parts Constructed");
                map.Add("2.40", "40. The Tabernacle is Set Up");
                map.Add("3.1", "1-3. The Sweet Savor Offerings");
                map.Add("3.2", "1-3. The Sweet Savor Offerings");
                map.Add("3.3", "1-3. The Sweet Savor Offerings");
                map.Add("3.4", "4-5. The Non-Sweet Savor Offerings");
                map.Add("3.5", "4-5. The Non-Sweet Savor Offerings");
                map.Add("3.6", "6-7. How to Apply the Five Offerings");
                map.Add("3.7", "6-7. How to Apply the Five Offerings");
                map.Add("3.8", "8. Consecration of the Priests");
                map.Add("3.9", "9. Beginning of the Priest's Ministry");
                map.Add("3.10", "10. Strange Fire'Nadab & Abihu");
                map.Add("3.11", "11. The Food of Israel");
                map.Add("3.12", "12. The Law of Motherhood");
                map.Add("3.13", "13. Leprosy!");
                map.Add("3.14", "14. Cleansing of the Leper");
                map.Add("3.15", "15. A Holy God, A Holy People");
                map.Add("3.16", "16. The Day of Atonement");
                map.Add("3.17", "17. Significance of Blood");
                map.Add("3.18", "18-20.How a Nation Falls");
                map.Add("3.19", "18-20.How a Nation Falls");
                map.Add("3.20", "18-20.How a Nation Falls");
                map.Add("3.21", "21-22. The Walk and Work of the Priests");
                map.Add("3.22", "21-22. The Walk and Work of the Priests");
                map.Add("3.23", "23. The Feasts of the Lord");
                map.Add("3.24", "24. Cursing and Capital Punishment");
                map.Add("3.25", "25. The Law of the Land (The Blessing and the Curse)");
                map.Add("3.26", "26. The Five Cycles of Discipline");
                map.Add("3.27", "27. Vows, First-Fruits, Dedications, the Tithe");
                map.Add("4.1", "1. The Numbering of the Tribes");
                map.Add("4.2", "2-9. The Arrangement of the Camp");
                map.Add("4.3", "2-9. The Arrangement of the Camp");
                map.Add("4.4", "2-9. The Arrangement of the Camp");
                map.Add("4.5", "2-9. The Arrangement of the Camp");
                map.Add("4.6", "2-9. The Arrangement of the Camp");
                map.Add("4.7", "2-9. The Arrangement of the Camp");
                map.Add("4.8", "2-9. The Arrangement of the Camp");
                map.Add("4.9", "2-9. The Arrangement of the Camp");
                map.Add("4.10", "10. Beginning of the March (Sinai to Kadesh Barnea)");
                map.Add("4.11", "11. The March Continues");
                map.Add("4.12", "12. The Murmuring of Miriam and Aaron against Moses");
                map.Add("4.13", "13. At Kadesh'the 12 Spies");
                map.Add("4.14", "14. The Unbelief of Israel at Kadesh");
                map.Add("4.15", "15-19.The Wandering in the Wilderness");
                map.Add("4.16", "15-19.The Wandering in the Wilderness");
                map.Add("4.17", "15-19.The Wandering in the Wilderness");
                map.Add("4.18", "15-19.The Wandering in the Wilderness");
                map.Add("4.19", "15-19.The Wandering in the Wilderness");
                map.Add("4.20", "20. No Water Situation #2");
                map.Add("4.21", "21. The Serpent of Brass");
                map.Add("4.22", "22-24.Balaam and Balak");
                map.Add("4.23", "22-24.Balaam and Balak");
                map.Add("4.24", "22-24.Balaam and Balak");
                map.Add("4.25", "25. The Doctrine of Balaam");
                map.Add("4.26", "26. New Generation Numbered");
                map.Add("4.27", "27. Moses Prepares to Die, Joshua Appointed");
                map.Add("4.28", "28-29. Instructions on Offerings");
                map.Add("4.29", "28-29. Instructions on Offerings");
                map.Add("4.30", "30. The Law of Vows");
                map.Add("4.31", "31. The Judgment on Midian");
                map.Add("4.32", "32. Reuben, Gad, '½ Tribe of Manasseh Choose Land East of Jordan");
                map.Add("4.33", "33. 40 Year Travelogue");
                map.Add("4.34", "34. The Borders of Canaan");
                map.Add("4.35", "35. The Cities of Refuge");
                map.Add("4.36", "36. Inheritance Laws (Keep it in the Family)");
                map.Add("5.1", "1-3. Moses' Sermon #1");
                map.Add("5.2", "1-3. Moses' Sermon #1");
                map.Add("5.3", "1-3. Moses' Sermon #1");
                map.Add("5.4", "4-11. Moses' Sermon #2");
                map.Add("5.5", "4-11. Moses' Sermon #2");
                map.Add("5.6", "4-11. Moses' Sermon #2");
                map.Add("5.7", "4-11. Moses' Sermon #2");
                map.Add("5.8", "4-11. Moses' Sermon #2");
                map.Add("5.9", "4-11. Moses' Sermon #2");
                map.Add("5.10", "4-11. Moses' Sermon #2");
                map.Add("5.11", "4-11. Moses' Sermon #2");
                map.Add("5.12", "12-27.Moses' Sermon #3");
                map.Add("5.13", "12-27.Moses' Sermon #3");
                map.Add("5.14", "12-27.Moses' Sermon #3");
                map.Add("5.15", "12-27.Moses' Sermon #3");
                map.Add("5.16", "12-27.Moses' Sermon #3");
                map.Add("5.17", "12-27.Moses' Sermon #3");
                map.Add("5.18", "12-27.Moses' Sermon #3");
                map.Add("5.19", "12-27.Moses' Sermon #3");
                map.Add("5.20", "12-27.Moses' Sermon #3");
                map.Add("5.21", "12-27.Moses' Sermon #3");
                map.Add("5.22", "12-27.Moses' Sermon #3");
                map.Add("5.23", "12-27.Moses' Sermon #3");
                map.Add("5.24", "12-27.Moses' Sermon #3");
                map.Add("5.25", "12-27.Moses' Sermon #3");
                map.Add("5.26", "12-27.Moses' Sermon #3");
                map.Add("5.27", "12-27.Moses' Sermon #3");
                map.Add("5.28", "28-30.Moses' Sermon #4");
                map.Add("5.29", "28-30.Moses' Sermon #4");
                map.Add("5.30", "28-30.Moses' Sermon #4");
                map.Add("5.31", "31. Moses' Sermon #5");
                map.Add("5.32", "32. Moses' Song & Benediction");
                map.Add("5.33", "33. Moses' Blessing on the Tribes");
                map.Add("5.34", "34. Moses' Look at Canaan, Death, Burial");
                map.Add("6.1", "1. Joshua Assumes Leadership");
                map.Add("6.2", "2. Rahab and the Spies");
                map.Add("6.3", "3. Crossing the Jordan");
                map.Add("6.4", "4. 2 Memorials (Jordan River & Gilgal)");
                map.Add("6.5", "5. The Unseen Captain");
                map.Add("6.6", "6. The Conquest of Jericho");
                map.Add("6.7", "7. Defeat at Ai");
                map.Add("6.8", "8. Victory at Ai");
                map.Add("6.9", "9. Deception of the Gibeonites");
                map.Add("6.10", "10. Gibeon Campaign & Southern Campaign");
                map.Add("6.11", "11. Final Conquest of Canaan");
                map.Add("6.12", "12. The 31 Kings");
                map.Add("6.13", "13-17.Division of the Land");
                map.Add("6.14", "13-17.Division of the Land");
                map.Add("6.15", "13-17.Division of the Land");
                map.Add("6.16", "13-17.Division of the Land");
                map.Add("6.17", "13-17.Division of the Land");
                map.Add("6.18", "18. The Tabernacle at Shiloh");
                map.Add("6.19", "19. Continued Division of the Land");
                map.Add("6.20", "20. The Cities of Refuge");
                map.Add("6.21", "21. Continued Division of the Land (Levites)");
                map.Add("6.22", "22. Rival, Schismatic Altar of Reuben & Gad");
                map.Add("6.23", "23. Last Counsels of Joshua");
                map.Add("6.24", "24. Joshua's Death");
                map.Add("7.1", "1. 'Neither Did' Chapter");
                map.Add("7.2", "2. Institution of the Judges");
                map.Add("7.3", "3. Gentlemen, Start Your Engines");
                map.Add("7.4", "4. Deborah & Barak");
                map.Add("7.5", "5. Song of Deborah & Barak");
                map.Add("7.6", "6. Gideon and the Fleece");
                map.Add("7.7", "7. Gideon's Victory, 300 Over Midian");
                map.Add("7.8", "8. 1st Jealousy of Ephraim; Death of Gideon");
                map.Add("7.9", "9. False King Abimelech");
                map.Add("7.10", "10. The Wickedness of Israel");
                map.Add("7.11", "11. Jephthah the 9th Judge");
                map.Add("7.12", "12. 2nd Jealousy of Ephraim");
                map.Add("7.13", "13. Samson's Parents");
                map.Add("7.14", "14. Samson's Riddle");
                map.Add("7.15", "15. Samson's Mighty Acts");
                map.Add("7.16", "16. Samson and Delilah");
                map.Add("7.17", "17. The Muddle of Micah");
                map.Add("7.18", "18. Danite Invasion & Idolatry");
                map.Add("7.19", "19. The Levite and His Concubine");
                map.Add("7.20", "20. Tribe of Benjamin Nearly Destroyed");
                map.Add("7.21", "21. How to Catch a Wife");
                map.Add("8.1", "1. Ruth & Naomi Return to Judah from Moab");
                map.Add("8.2", "2. Ruth Harvests in Boaz's Fields");
                map.Add("8.3", "3. Ruth and the Law of the Kinsman Redeemer");
                map.Add("8.4", "4. Ruth Marries Boaz");
                map.Add("9.1", "1. Hannah and the Birth of Samuel");
                map.Add("9.2", "2. Samuel, Eli, Eli's Evil Sons");
                map.Add("9.3", "3. The Call of Samuel");
                map.Add("9.4", "4. Defeat, Ark Lost to Philistines");
                map.Add("9.5", "5. Dagon vs. the Ark");
                map.Add("9.6", "6. Ark Returned");
                map.Add("9.7", "7. Ark at Home");
                map.Add("9.8", "8. Israel Demands a King");
                map.Add("9.9", "9. Saul Chosen");
                map.Add("9.10", "10. Saul's Anointing");
                map.Add("9.11", "11. Saul's Victory");
                map.Add("9.12", "12. Samuel's Valedictory Address");
                map.Add("9.13", "13. Saul's Rejection by God");
                map.Add("9.14", "14. Jonathan's Victory over the Philistines");
                map.Add("9.15", "15. Saul's Sheep Lie");
                map.Add("9.16", "16. David Chosen and Anointed");
                map.Add("9.17", "17. David & Goliath");
                map.Add("9.18", "18. David & Jonathan");
                map.Add("9.19", "19. David Flees from Saul");
                map.Add("9.20", "20. Jonathan Protects David");
                map.Add("9.21", "21. David Continues to Flee");
                map.Add("9.22", "22. David's Mighty Men");
                map.Add("9.23", "23. Their Adventures");
                map.Add("9.24", "24. David Spares Saul #1");
                map.Add("9.25", "25. Samuel Dies");
                map.Add("9.26", "26. David Spares Saul #2");
                map.Add("9.27", "27. David's Backsliding in Philistia");
                map.Add("9.28", "28. Saul and the Witch of Endor");
                map.Add("9.29", "29. David & Achish");
                map.Add("9.30", "30. David and Ziklag (2 Wives Captured)");
                map.Add("9.31", "31. The Death of Saul");
                map.Add("10.1", "1. Saul & Jonathan's Death Told to David");
                map.Add("10.2", "2. Civil War'Abner vs. David");
                map.Add("10.3", "3. Civil War'House of Saul vs. David");
                map.Add("10.4", "4. The Murder of Ish-Bosheth");
                map.Add("10.5", "5. David Becomes King over Israel");
                map.Add("10.6", "6. Ark to Jerusalem");
                map.Add("10.7", "7. The Davidic Covenant Stated");
                map.Add("10.8", "8. David the Mighty Conqueror");
                map.Add("10.9", "9. David & Mephibosheth");
                map.Add("10.10", "10. The Ammonite-Syrian War");
                map.Add("10.11", "11. David's Sin with Bathsheba");
                map.Add("10.12", "12. David's Confession of Sin");
                map.Add("10.13", "13. Amnon's Crime (Immorality)");
                map.Add("10.14", "14. Beautiful Absalom");
                map.Add("10.15", "15. Absalom's Rebellion");
                map.Add("10.16", "16. Absalom Enters Jerusalem");
                map.Add("10.17", "17. Absalom Listens to False Counselors");
                map.Add("10.18", "18. Absalom Hangs by His Hair & Dies");
                map.Add("10.19", "19. David Gets With It");
                map.Add("10.20", "20. Sheba's Revolt");
                map.Add("10.21", "21. Three Years Famine");
                map.Add("10.22", "22. David's Son of Deliverance");
                map.Add("10.23", "23. David's Mighty Men");
                map.Add("10.24", "24. David's Numbering Sin");
                map.Add("11.1", "1. David Failing, Solomon Anointed");
                map.Add("11.2", "2. The Death of David");
                map.Add("11.3", "3. Solomon's Prayer for Wisdom");
                map.Add("11.4", "4. Solomon Gets Wisdom");
                map.Add("11.5", "5-8. Solomon's Temple'The Building and Dedication");
                map.Add("11.6", "5-8. Solomon's Temple'The Building and Dedication");
                map.Add("11.7", "5-8. Solomon's Temple'The Building and Dedication");
                map.Add("11.8", "5-8. Solomon's Temple'The Building and Dedication");
                map.Add("11.9", "9. Solomon's Fame and Wealth");
                map.Add("11.10", "10. Solomon & the Queen of Sheba");
                map.Add("11.11", "11. The Backsliding and Death of Solomon");
                map.Add("11.12", "12. Split of the Kingdom (Rehoboam, Solomon's Son in the South)");
                map.Add("11.13", "13. A Wicked Jeroboam");
                map.Add("11.14", "14. Jeroboam and Rehoboam Die");
                map.Add("11.15", "15. Abijam, Asa, Baasha, Nabad");
                map.Add("11.16", "16. Some of Israel's Wicked Kings (Elah, Zimri, Tibni, Omri, Ahab)");
                map.Add("11.17", "17. Elijah Fed by Ravens, Raising of the Widow's Son");
                map.Add("11.18", "18. Elijah vs. Baal (Mt. Carmel)");
                map.Add("11.19", "19. Elijah & Still, Small Voice");
                map.Add("11.20", "20. Ahab and Victory over Syrians");
                map.Add("11.21", "21. Ahab, Jezebel");
                map.Add("11.22", "22. Micaiah'God's Man of Conviction");
                map.Add("12.1", "1. Elijah'Illness & Death of Ahaziah");
                map.Add("12.2", "2. Elijah's Translation");
                map.Add("12.3", "3. Elisha'Defeat of the Moabites");
                map.Add("12.4", "4. Elisha's 5 Miracle Chapter");
                map.Add("12.5", "5. The Healing of Naaman");
                map.Add("12.6", "6. Elisha and the Lost Axe Head");
                map.Add("12.7", "7. Elisha: 'You Will Eat!'");
                map.Add("12.8", "8. Elisha Predicts 7 Years of Famine");
                map.Add("12.9", "9. Jehu the Furious Driver");
                map.Add("12.10", "10. Judgment on Ahab's 70 Sons");
                map.Add("12.11", "11. Only One Heir'Joash");
                map.Add("12.12", "12. Repairing of the Temple");
                map.Add("12.13", "13. Elisha Dies");
                map.Add("12.14", "14. Civil War'Israel & Judah");
                map.Add("12.15", "15. Various Kings of Israel");
                map.Add("12.16", "16. Rule of Ahaz");
                map.Add("12.17", "17. Assyrian Captivity and Why");
                map.Add("12.18", "18. Reign of Hezekiah");
                map.Add("12.19", "19. Isaiah and Hezekiah");
                map.Add("12.20", "20. Hezekiah's 15 Year Extension & Death");
                map.Add("12.21", "21. Evil King Manasseh");
                map.Add("12.22", "22. Josiah'Rediscovery of the Law");
                map.Add("12.23", "23. Word Read and Passover Kept");
                map.Add("12.24", "24. Babylon Captivity'70 Years");
                map.Add("12.25", "25. Babylon Captivity'Siege of Jerusalem");
                map.Add("13.1", "1-9. Genealogies");
                map.Add("13.2", "1-9. Genealogies");
                map.Add("13.3", "1-9. Genealogies");
                map.Add("13.4", "1-9. Genealogies");
                map.Add("13.5", "1-9. Genealogies");
                map.Add("13.6", "1-9. Genealogies");
                map.Add("13.7", "1-9. Genealogies");
                map.Add("13.8", "1-9. Genealogies");
                map.Add("13.9", "1-9. Genealogies");
                map.Add("13.10", "10. Saul's Death");
                map.Add("13.11", "11-12.David's Mighty Men");
                map.Add("13.12", "11-12.David's Mighty Men");
                map.Add("13.13", "13. Uzza and the Ark");
                map.Add("13.14", "14. David and the Mulberry Trees");
                map.Add("13.15", "15. Ark Returned");
                map.Add("13.16", "16. David and a Psalm");
                map.Add("13.17", "17. The Davidic Covenant");
                map.Add("13.18", "18. David's Mighty Kingdom (then)");
                map.Add("13.19", "19. The Ammonite-Syrian War");
                map.Add("13.20", "20. The Giant with 24 Fingers and Toes");
                map.Add("13.21", "21. David's Numbering Sin");
                map.Add("13.22", "22. David Prepares Materials for the Temple");
                map.Add("13.23", "23. Solomon Made King, Organization of Levitical Priests");
                map.Add("13.24", "24-27.Organization of Israel Continued");
                map.Add("13.25", "24-27.Organization of Israel Continued");
                map.Add("13.26", "24-27.Organization of Israel Continued");
                map.Add("13.27", "24-27.Organization of Israel Continued");
                map.Add("13.28", "28-29.Closing Counsel of David, Teenage Solomon Reigns, David Dies");
                map.Add("13.29", "28-29.Closing Counsel of David, Teenage Solomon Reigns, David Dies");
                map.Add("14.1", "1. Solomon and His Wisdom");
                map.Add("14.2", "2-4. Solomon Builds the Temple");
                map.Add("14.3", "2-4. Solomon Builds the Temple");
                map.Add("14.4", "2-4. Solomon Builds the Temple");
                map.Add("14.5", "5. Ark Put in Temple, Glory Fills the Temple");
                map.Add("14.6", "6. Solomon Dedicates the Temple");
                map.Add("14.7", "7. The Lord is Pleased");
                map.Add("14.8", "8. Solomon's Activity and Wealth");
                map.Add("14.9", "9. Solomon and the Queen of Sheba");
                map.Add("14.10", "10-12.Rehoboam Over 2 Southern Tribes");
                map.Add("14.11", "10-12.Rehoboam Over 2 Southern Tribes");
                map.Add("14.12", "10-12.Rehoboam Over 2 Southern Tribes");
                map.Add("14.13", "13. Jeroboam Over 10 Northern Tribes");
                map.Add("14.14", "14-16.Good King Asa");
                map.Add("14.15", "14-16.Good King Asa");
                map.Add("14.16", "14-16.Good King Asa");
                map.Add("14.17", "17-20.Good King Jehoshaphat");
                map.Add("14.18", "17-20.Good King Jehoshaphat");
                map.Add("14.19", "17-20.Good King Jehoshaphat");
                map.Add("14.20", "17-20.Good King Jehoshaphat");
                map.Add("14.21", "21. Jehoram's Reign [J]");
                map.Add("14.22", "22. Only One Heir Left in the Royal Line of Christ, Joash");
                map.Add("14.23", "23-24.Reign of Joash [J]");
                map.Add("14.24", "23-24.Reign of Joash [J]");
                map.Add("14.25", "25. Reign of Amaziah [J]");
                map.Add("14.26", "26. Reign of Uzziah [J]");
                map.Add("14.27", "27. Reign of Jothan [J]");
                map.Add("14.28", "28. Reign of Ahaz [J]");
                map.Add("14.29", "29-32.Reign of Hezekiah [J]");
                map.Add("14.30", "29-32.Reign of Hezekiah [J]");
                map.Add("14.31", "29-32.Reign of Hezekiah [J]");
                map.Add("14.32", "29-32.Reign of Hezekiah [J]");
                map.Add("14.33", "33. Reign of Manasseh (55) [J]");
                map.Add("14.34", "34-35.Reign of Josiah [J]");
                map.Add("14.35", "34-35.Reign of Josiah [J]");
                map.Add("14.36", "36. The Babylonian Captivity");
                map.Add("15.1", "1. Decree of Cyrus (Restoration of the Temple)");
                map.Add("15.2", "2. The Returning Remnant");
                map.Add("15.3", "3. Temple Foundations Laid");
                map.Add("15.4", "4. Opposition, Letter to Artaxerxes, Work Stopped");
                map.Add("15.5", "5. Opposition Answered");
                map.Add("15.6", "6. Decree of Darius (Temple Finished)");
                map.Add("15.7", "7. Ezra Thanks the Lord");
                map.Add("15.8", "8. Treasure Brought to the Temple");
                map.Add("15.9", "9. Unholy (Mixed) Marriages, Ezra's Prayer");
                map.Add("15.10", "10. The Above Sin is Judged and Restitution Made");
                map.Add("16.1", "1. The Ruined Walls");
                map.Add("16.2", "2. Nehemiah Surveys the Ruins");
                map.Add("16.3", "3. The Builders Begin to Build");
                map.Add("16.4", "4-6. Opposition in the Rebuilding");
                map.Add("16.5", "4-6. Opposition in the Rebuilding");
                map.Add("16.6", "4-6. Opposition in the Rebuilding");
                map.Add("16.7", "7. Genealogies");
                map.Add("16.8", "8. Ezra's Expository Preaching");
                map.Add("16.9", "9. Review of Old Testament History");
                map.Add("16.10", "10. Application of Teaching to Experience");
                map.Add("16.11", "11. Geographical Distribution of the Inhabitants of Israel");
                map.Add("16.12", "12. Dedication of the Walls");
                map.Add("16.13", "13. The Law and Separation");

                // Esther
                map.Add("17.1", "1. Queen Vashti Disobeys the King");
                map.Add("17.2", "2. Queen Esther the Jew");
                map.Add("17.3", "3. Mordecai and Haman");
                map.Add("17.4", "4. Planned Extermination of the Jewish Nation");
                map.Add("17.5", "5. 'If I Perish, I Perish'");
                map.Add("17.6", "6. Haman Shamed");
                map.Add("17.7", "7. Haman Hanged");
                map.Add("17.8", "8. The Jews Delivered");
                map.Add("17.9", "9. The Feast of Purim (Celebrating Jewish Deliverance)");
                map.Add("17.10", "10. Mordecai, 2nd in the Kingdom");

                // Job
                map.Add("18.1", "1. Job and Suffering (Family)");
                map.Add("18.2", "2-3. Job and Suffering (Personal)");
                map.Add("18.3", "2-3. Job and Suffering (Personal)");
                map.Add("18.4", "4-5. Eliphaz's First Prosecution");
                map.Add("18.5", "4-5. Eliphaz's First Prosecution");
                map.Add("18.6", "6-7. Job's Defense");
                map.Add("18.7", "6-7. Job's Defense");
                map.Add("18.8", "8. Bildad's First Prosecution");
                map.Add("18.9", "9-10. Job's Defense");
                map.Add("18.10", "9-10. Job's Defense");
                map.Add("18.11", "11. Zophar's First Prosecution");
                map.Add("18.12", "12-14. Job's Defense");
                map.Add("18.13", "12-14. Job's Defense");
                map.Add("18.14", "12-14. Job's Defense");
                map.Add("18.15", "15. Eliphaz's Second Prosecution");
                map.Add("18.16", "16-17. Job's Defense");
                map.Add("18.17", "16-17. Job's Defense");
                map.Add("18.18", "18. Bildad's Second Prosecution");
                map.Add("18.19", "19. Job's Defense");
                map.Add("18.20", "20. Zophar's Final Arguments");
                map.Add("18.21", "21. Job's Defense");
                map.Add("18.22", "22. Eliphaz's Final Arguments");
                map.Add("18.23", "23-24. Job's Defense");
                map.Add("18.24", "23-24. Job's Defense");
                map.Add("18.25", "25. Bildad's Final Arguments");
                map.Add("18.26", "26-31. Job's Defense");
                map.Add("18.27", "26-31. Job's Defense");
                map.Add("18.28", "26-31. Job's Defense");
                map.Add("18.29", "26-31. Job's Defense");
                map.Add("18.30", "26-31. Job's Defense");
                map.Add("18.31", "26-31. Job's Defense");
                map.Add("18.32", "32-37.The Speech of Elihu");
                map.Add("18.33", "32-37.The Speech of Elihu");
                map.Add("18.34", "32-37.The Speech of Elihu");
                map.Add("18.35", "32-37.The Speech of Elihu");
                map.Add("18.36", "32-37.The Speech of Elihu");
                map.Add("18.37", "32-37.The Speech of Elihu");
                map.Add("18.38", "38-41.God Talks to Job");
                map.Add("18.39", "38-41.God Talks to Job");
                map.Add("18.40", "38-41.God Talks to Job");
                map.Add("18.41", "38-41.God Talks to Job");
                map.Add("18.42", "42. Job's Confessions & Restoration");
                map.Add("19.1", "1. The Blessed Man");
                map.Add("19.2", "2. The King Rejected but Coming to Reign");
                map.Add("19.3", "3. A Psalm in Distress");
                map.Add("19.4", "4. Prayer in Trouble");
                map.Add("19.5", "5. Sharing God's Attitude Toward Sin");
                map.Add("19.6", "6. Praying in Deepest Distress");
                map.Add("19.7", "7. The Slandered Saint Psalm");
                map.Add("19.8", "8. The Son of Man Reigning");
                map.Add("19.9", "9. Praise for Righteous Judgment");
                map.Add("19.10", "10. A Psalm Concerning the Wicked");
                map.Add("19.11", "11. The Psalm of the Steadfast");
                map.Add("19.12", "12. Liars Against the Truth");
                map.Add("19.13", "13. The 'How Long' Psalm");
                map.Add("19.14", "14. The Psalm of the Fool");
                map.Add("19.15", "15. The Regenerate Described");
                map.Add("19.16", "16. Death and Resurrection");
                map.Add("19.17", "17. A Prayer of David Against the Wicked");
                map.Add("19.18", "18. David's Psalm of Deliverance");
                map.Add("19.19", "19. The Witness of Creation and Revelation");
                map.Add("19.20", "20. A Psalm for a Day of Trouble");
                map.Add("19.21", "21. Victorious King Psalm");
                map.Add("19.22", "22. The Good Shepherd (Crucified)");
                map.Add("19.23", "23. The Great Shepherd (Risen)");
                map.Add("19.24", "24. The Chief Shepherd (Coming)");
                map.Add("19.25", "25. Trust in the Midst of Trouble");
                map.Add("19.26", "26. How to Avoid Backsliding");
                map.Add("19.27", "27. One Desire in Time of Trouble");
                map.Add("19.28", "28. A Cry for Judgment");
                map.Add("19.29", "29. The Judgment Storm");
                map.Add("19.30", "30. A Psalm of Dedication");
                map.Add("19.31", "31. A Psalm of Trouble and Trust");
                map.Add("19.32", "32. David's Testimony of Confession");
                map.Add("19.33", "33. Praise for Creation, Providence, Grace");
                map.Add("19.34", "34. Appreciation for Deliverance");
                map.Add("19.35", "35. A Prayer for Intercessors");
                map.Add("19.36", "36. Wicked Way and God's Way Contrasted");
                map.Add("19.37", "37. 'Fret Not' Psalm");
                map.Add("19.38", "38. David, Out of Fellowship, In at End");
                map.Add("19.39", "39. Prayer for Wisdom");
                map.Add("19.40", "40. The Obedience of Christ, New Song");
                map.Add("19.41", "41. Prophesied Betrayal by Judas");
                map.Add("19.42", "42. 'Hope Thou in God' Psalm");
                map.Add("19.43", "43. Enemies Bug Me");
                map.Add("19.44", "44. Undeserved Suffering");
                map.Add("19.45", "45. Royal Wedding Psalm");
                map.Add("19.46", "46. Triumph in the Great Tribulation Period");
                map.Add("19.47", "47. The Lord Reigning");
                map.Add("19.48", "48. Jerusalem");
                map.Add("19.49", "49. The Folly of Unbelief");
                map.Add("19.50", "50. The Nature of True Worship");
                map.Add("19.51", "51. David's Sin Acknowledged");
                map.Add("19.52", "52. 'Green Olive Tree' Psalm");
                map.Add("19.53", "53. The Psalm of the Fool (Same as Psalm 14)");
                map.Add("19.54", "54. 'Mine Helper' Psalm");
                map.Add("19.55", "55. Escape From Tribulation");
                map.Add("19.56", "56. A Prayer of the Hunted One");
                map.Add("19.57", "57. Refuge in Trouble");
                map.Add("19.58", "58. Imprecatory Psalm");
                map.Add("19.59", "59. Prayer for Deliverance and Judgment");
                map.Add("19.60", "60. Through Defeat to Victory");
                map.Add("19.61", "61. Refuge in the Rock");
                map.Add("19.62", "62. Confidence in God the Rock");
                map.Add("19.63", "63. 'Most Beautiful' Psalm");
                map.Add("19.64", "64. Wicked vs. the Righteous");
                map.Add("19.65", "65. Thanksgiving Psalm");
                map.Add("19.66", "66. Worthy Worship Psalm");
                map.Add("19.67", "67. Future Kingdom Blessing");
                map.Add("19.68", "68. Victorious Procession of God");
                map.Add("19.69", "69. The Sufferings of Christ");
                map.Add("19.70", "70. Memorial Psalm");
                map.Add("19.71", "71. Aged Saint Psalm");
                map.Add("19.72", "72. King and the Kingdom");
                map.Add("19.73", "73. Envious at the Prosperity of the Wicked");
                map.Add("19.74", "74. The Enemy in Possession");
                map.Add("19.75", "75. The Lord's Cup of Judgment");
                map.Add("19.76", "76. When God Reigns in Zion");
                map.Add("19.77", "77. The Troubled Saint");
                map.Add("19.78", "78. The History of God's Grace With Israel");
                map.Add("19.79", "79. A Prayer With Jerusalem in Ruins!");
                map.Add("19.80", "80. Christ, the Strong Man");
                map.Add("19.81", "81. God Bares the Heart");
                map.Add("19.82", "82. God is the Judge");
                map.Add("19.83", "83. Afflicted to Learn!");
                map.Add("19.84", "84. 'Sons of Grace' Psalm");
                map.Add("19.85", "85. 'Revival Prayer' Psalm");
                map.Add("19.86", "86. Poor and Needy Prayer");
                map.Add("19.87", "87. A Song of Zion");
                map.Add("19.88", "88. 'Deepest Distress' Psalm");
                map.Add("19.89", "89. 'Davidic Covenant' Psalm");
                map.Add("19.90", "90. The Psalm of Death (First Adam)");
                map.Add("19.91", "91. The Psalm of Life (Last Adam)");
                map.Add("19.92", "92. Sabbath Palm (of rest)");
                map.Add("19.93", "93. The King and His Throne");
                map.Add("19.94", "94. A Prayer for Vengeance");
                map.Add("19.95", "95. A Psalm of Praise and Warning");
                map.Add("19.96", "96. Praise and Testimony in View of the Second Advent");
                map.Add("19.97", "97. 'The Lord Reigneth' Psalm");
                map.Add("19.98", "98. A New Song of Victory");
                map.Add("19.99", "99. Righteous Judgment & Trembling");
                map.Add("19.100", "100. The Old Hundreth (Thanksgiving)");
                map.Add("19.101", "101. The King and His Subjects");
                map.Add("19.102", "102. A Prayer in Humiliation");
                map.Add("19.103", "103. 'Bless the Lord, O My Soul' Psalm");
                map.Add("19.104", "104. The Praise of His Works");
                map.Add("19.105", "105. Israel's History & God's Mercy");
                map.Add("19.106", "106. Israel's Failure & God's Grace");
                map.Add("19.107", "107. Thanksgiving for Affliction");
                map.Add("19.108", "108. Praise for Victory");
                map.Add("19.109", "109. 'Satanic Power' Psalm");
                map.Add("19.110", "110. Christ as King and Priest");
                map.Add("19.111", "111. 'Reverend is His Name' Psalm");
                map.Add("19.112", "112. God's Plan is Greater than the Pressures of Life");
                map.Add("19.113", "113. From Dunghill to Ruler");
                map.Add("19.114", "114. When Israel Went Out of Egypt");
                map.Add("19.115", "115. God Compared With Idols");
                map.Add("19.116", "116. 'Dying Grace' Psalm");
                map.Add("19.117", "117. The Shortest Psalm (praise)");
                map.Add("19.118", "118. The Exalted Christ");
                map.Add("19.119", "119. 'The Word of God' Psalm");
                map.Add("19.120", "120. Prayer Against a Lying Tongue");
                map.Add("19.121", "121. The Traveler's Psalm");
                map.Add("19.122", "122. Jerusalem and Peace");
                map.Add("19.123", "123. Waiting in Faith");
                map.Add("19.124", "124. Lord on our Side");
                map.Add("19.125", "125. Security for the Trusting");
                map.Add("19.126", "126. A Psalm of Freedom");
                map.Add("19.127", "127. Safety in the Lord");
                map.Add("19.128", "128. Earthly Blessings");
                map.Add("19.129", "129. Comfort in Affliction");
                map.Add("19.130", "130. Who Shall Stand?");
                map.Add("19.131", "131. Childlike Trust");
                map.Add("19.132", "132. Davidic Covenant Psalm");
                map.Add("19.133", "133. A Psalm of Fellowship");
                map.Add("19.134", "134. Worship at Night");
                map.Add("19.135", "135. Priestly Praise Psalm");
                map.Add("19.136", "136. His Mercy Endureth Forever");
                map.Add("19.137", "137. Babylon Captivity Weeping");
                map.Add("19.138", "138. 'Magnified Thy Word Above Thy Name' Psalm");
                map.Add("19.139", "139. Spiritual Life Psalm");
                map.Add("19.140", "140. Opposition from Evil");
                map.Add("19.141", "141. 'Guard My Speech' Psalm");
                map.Add("19.142", "142. The Prisoner's Psalm");
                map.Add("19.143", "143. A Prayer for Mercy in Persecution");
                map.Add("19.144", "144. Military Strength Psalm");
                map.Add("19.145", "145. Pure Praise Psalm");
                map.Add("19.146", "146. Praise and Trust");
                map.Add("19.147", "147. Praise for God's Grace to Israel");
                map.Add("19.148", "148. Praise from all Creation");
                map.Add("19.149", "149. A New Song of Praise");
                map.Add("19.150", "150. Praise Ye the Lord");
                map.Add("19.151", "151. A hallelujah of David, Jesse's son.");

                map.Add("20.1", "1. Introduction to Wisdom");
                map.Add("20.2", "2. Seek Bible Doctrine Wholeheartedly");
                map.Add("20.3", "3-4. Elaboration on Bible Doctrine");
                map.Add("20.4", "3-4. Elaboration on Bible Doctrine");
                map.Add("20.5", "5-7. Illegitimate Love Condemned");
                map.Add("20.6", "5-7. Illegitimate Love Condemned");
                map.Add("20.7", "5-7. Illegitimate Love Condemned");
                map.Add("20.8", "8-9. Good Women vs. Bad Women");
                map.Add("20.9", "8-9. Good Women vs. Bad Women");
                map.Add("20.10", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.11", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.12", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.13", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.14", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.15", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.16", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.17", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.18", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.19", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.20", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.21", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.22", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.23", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.24", "10-24.Application of Bible Doctrine to Experience");
                map.Add("20.25", "25-29.Proverbs Concerning the Fool");
                map.Add("20.26", "25-29.Proverbs Concerning the Fool");
                map.Add("20.27", "25-29.Proverbs Concerning the Fool");
                map.Add("20.28", "25-29.Proverbs Concerning the Fool");
                map.Add("20.29", "25-29.Proverbs Concerning the Fool");
                map.Add("20.30", "30. Words of Agur");
                map.Add("20.31", "31. A Virtuous Woman");
                map.Add("21.1", "1. Nothing Satisfies the Carnal Believer");
                map.Add("21.2", "2. Pleasures & Materialism Do Not Satisfy");
                map.Add("21.3", "3-4. Egotism Does Not Satisfy");
                map.Add("21.4", "3-4. Egotism Does Not Satisfy");
                map.Add("21.5", "5-6. Empty Religion and Wealth Do Not Satisfy");
                map.Add("21.6", "5-6. Empty Religion and Wealth Do Not Satisfy");
                map.Add("21.7", "7-12. Humanitarian Works Do Not Satisfy");
                map.Add("21.8", "7-12. Humanitarian Works Do Not Satisfy");
                map.Add("21.9", "7-12. Humanitarian Works Do Not Satisfy");
                map.Add("21.10", "7-12. Humanitarian Works Do Not Satisfy");
                map.Add("21.11", "7-12. Humanitarian Works Do Not Satisfy");
                map.Add("21.12", "7-12. Humanitarian Works Do Not Satisfy");
                map.Add("22.1", "1. Conversation Between Shulamite Woman and the Daughters of Jerusalem");
                map.Add("22.2", "2. The Shulamite's Thoughts of Her Shepherd Lover");
                map.Add("22.3", "3. The Woman's Search for Her Lover, Her Desire to Marry Him, Glimpse of Rival Lover Solomon in all His Glory.");
                map.Add("22.4", "4. The Wooing of King Solomon, She Says No");
                map.Add("22.5", "5. The Woman's Thoughts Concerning Her Shepherd Lover");
                map.Add("22.6", "6. Solomon Woos, She Refuses");
                map.Add("22.7", "7. The Shulamite Woman Escapes");
                map.Add("22.8", "8. Shulamite Lover and Shepherd Lover Together Again in their Home Town.");
                map.Add("23.1", "1. Terrible Wickedness of Judah");
                map.Add("23.2", "2-4. Preview of the Millennial Age");
                map.Add("23.3", "2-4. Preview of the Millennial Age");
                map.Add("23.4", "2-4. Preview of the Millennial Age");
                map.Add("23.5", "5. Vineyard Funeral Dirge");
                map.Add("23.6", "6. The Call of Isaiah");
                map.Add("23.7", "7. The Virgin Birth Chapter");
                map.Add("23.8", "8. Maher-shalal-hash-baz");
                map.Add("23.9", "9. Names of Christ Prophesied");
                map.Add("23.10", "10. The Advancing Assyrians");
                map.Add("23.11", "11-12.The Branch and Millennial Kingdom");
                map.Add("23.12", "11-12.The Branch and Millennial Kingdom");
                map.Add("23.13", "13-14. Fall of Babylon & Philistia");
                map.Add("23.14", "13-14. Fall of Babylon & Philistia");
                map.Add("23.15", "15-16.Moab");
                map.Add("23.16", "15-16.Moab");
                map.Add("23.17", "17. Damascus");
                map.Add("23.18", "18. Ethiopia");
                map.Add("23.19", "19. Egypt");
                map.Add("23.20", "20-21.Egypt and Ethiopia, Babylon, Edom, Arabia");
                map.Add("23.21", "20-21.Egypt and Ethiopia, Babylon, Edom, Arabia");
                map.Add("23.22", "22. Jerusalem");
                map.Add("23.23", "23. Tyre");
                map.Add("23.24", "24. Tribulational Troubles");
                map.Add("23.25", "25. Millennial Mercies");
                map.Add("23.26", "26. 'Thou Wilt Keep Him in Perfect Peace'");
                map.Add("23.27", "27. Israel Regathered");
                map.Add("23.28", "28. Denouncing Samaria and Jerusalem");
                map.Add("23.29", "29. Imminent Siege of Jerusalem");
                map.Add("23.30", "30-31. Judah's Alliance With Egypt");
                map.Add("23.31", "30-31. Judah's Alliance With Egypt");
                map.Add("23.32", "32-34. Preparation for Armageddon");
                map.Add("23.33", "32-34. Preparation for Armageddon");
                map.Add("23.34", "32-34. Preparation for Armageddon");
                map.Add("23.35", "35. The Regathering of Israel (2nd Advent)");
                map.Add("23.36", "36-37.Assyrian Army Defeated");
                map.Add("23.37", "36-37.Assyrian Army Defeated");
                map.Add("23.38", "38-39.Hezekiah's Sickness and Death");
                map.Add("23.39", "38-39.Hezekiah's Sickness and Death");
                map.Add("23.40", "40-44.Words of Comfort");
                map.Add("23.41", "40-44.Words of Comfort");
                map.Add("23.42", "40-44.Words of Comfort");
                map.Add("23.43", "40-44.Words of Comfort");
                map.Add("23.44", "40-44.Words of Comfort");
                map.Add("23.45", "45. Prophecy of Cyrus");
                map.Add("23.46", "46-48. Fall of Babylon");
                map.Add("23.47", "46-48. Fall of Babylon");
                map.Add("23.48", "46-48. Fall of Babylon");
                map.Add("23.49", "49-57. The Great Deliverer'God");
                map.Add("23.50", "49-57. The Great Deliverer'God");
                map.Add("23.51", "49-57. The Great Deliverer'God");
                map.Add("23.52", "49-57. The Great Deliverer'God");
                map.Add("23.53", "49-57. The Great Deliverer'God");
                map.Add("23.54", "49-57. The Great Deliverer'God");
                map.Add("23.55", "49-57. The Great Deliverer'God");
                map.Add("23.56", "49-57. The Great Deliverer'God");
                map.Add("23.57", "49-57. The Great Deliverer'God");
                map.Add("23.58", "58-59.Comparison of the Faithful and Unfaithful");
                map.Add("23.59", "58-59.Comparison of the Faithful and Unfaithful");
                map.Add("23.60", "60-62. The Glorious Redeemer, Jerusalem & its Citizens");
                map.Add("23.61", "60-62. The Glorious Redeemer, Jerusalem & its Citizens");
                map.Add("23.62", "60-62. The Glorious Redeemer, Jerusalem & its Citizens");
                map.Add("23.63", "63-64.Repentance and Confession");
                map.Add("23.64", "63-64.Repentance and Confession");
                map.Add("23.65", "65-66.New Heavens and New Earth");
                map.Add("23.66", "65-66.New Heavens and New Earth");
                map.Add("24.1", "1. The Prophet's Call");
                map.Add("24.2", "2. Israel's Apostasy");
                map.Add("24.3", "3. Judah Worse Than Israel!");
                map.Add("24.4", "4. Approaching Desolation of Judah");
                map.Add("24.5", "5. Universal Depravity of Judah");
                map.Add("24.6", "6. Destruction From the North (Prophetic)");
                map.Add("24.7", "7. Repentance Their Only Hope");
                map.Add("24.8", "8. The Harvest is Past");
                map.Add("24.9", "9. Jeremiah, the Weeping Prophet");
                map.Add("24.10", "10. Jehovah, the True God");
                map.Add("24.11", "11. The Broken Covenant'Jeremiah's Death Plotted");
                map.Add("24.12", "12. Jeremiah's Complaint");
                map.Add("24.13", "13. The Ruined Waistband");
                map.Add("24.14", "14-15.Drought and Jeremiah's Intercession");
                map.Add("24.15", "14-15.Drought and Jeremiah's Intercession");
                map.Add("24.16", "16. Jeremiah Forbidden to Marry");
                map.Add("24.17", "17. Sabbath Profaned, Judgment Inevitable");
                map.Add("24.18", "18. The Potter's Clay");
                map.Add("24.19", "19. The Earthen Bottle Broken");
                map.Add("24.20", "20. Jeremiah Imprisoned, Discouraged");
                map.Add("24.21", "21. The Siege Begins");
                map.Add("24.22", "22. Warning to King Jehoiakim");
                map.Add("24.23", "23. False Prophets");
                map.Add("24.24", "24. The Two Baskets of Figs");
                map.Add("24.25", "25. 70 Years of Captivity Predicted");
                map.Add("24.26", "26. Jeremiah's Trial Before the Princes");
                map.Add("24.27", "27-28.Oxen Yoke on Jeremiah's Neck");
                map.Add("24.28", "27-28.Oxen Yoke on Jeremiah's Neck");
                map.Add("24.29", "29. Jeremiah's Letter to Those in Exile");
                map.Add("24.30", "30. The Great Tribulation");
                map.Add("24.31", "31. The New Covenant");
                map.Add("24.32", "32-33.Nature of the New Covenant");
                map.Add("24.33", "32-33.Nature of the New Covenant");
                map.Add("24.34", "34. Zedekiah's Proclamation of Liberty");
                map.Add("24.35", "35. The Obedience of the Rechabites");
                map.Add("24.36", "36. The King Throws Jeremiah's Book into the Fire");
                map.Add("24.37", "37-38. Jeremiah's Imprisonment");
                map.Add("24.38", "37-38. Jeremiah's Imprisonment");
                map.Add("24.39", "39. Jerusalem Burned");
                map.Add("24.40", "40-41.Gedaliah Made Governor");
                map.Add("24.41", "40-41.Gedaliah Made Governor");
                map.Add("24.42", "42-43.Remnant Goes to Egypt");
                map.Add("24.43", "42-43.Remnant Goes to Egypt");
                map.Add("24.44", "44. Jeremiah's Final Appeal");
                map.Add("24.45", "45. Baruch (Jeremiah's Scribe)");
                map.Add("24.46", "46. Prophecy against Egypt");
                map.Add("24.47", "47. Prophecy against the Philistines");
                map.Add("24.48", "48. Prophecy against Moab");
                map.Add("24.49", "49. Prophecy against Ammon, Edom, Syria, Hazor, Elam");
                map.Add("24.50", "50-51.Prediction of the Fall of Babylon");
                map.Add("24.51", "50-51.Prediction of the Fall of Babylon");
                map.Add("24.52", "52. Historical Appendix");
                map.Add("25.1", "1. The Departure of Judah");
                map.Add("25.2", "2. The Devastation of Jehovah");
                map.Add("25.3", "3. The Discernment of Jeremiah");
                map.Add("25.4", "4. The Discipline of Jehovah");
                map.Add("25.5", "5. The Deterrent for Judah");
                map.Add("26.1", "1. The Vision of the Glory of God");
                map.Add("26.2", "2-3. The Voice of God");
                map.Add("26.3", "2-3. The Voice of God");
                map.Add("26.4", "4-7. Symbolic Seige of Jerusalem");
                map.Add("26.5", "4-7. Symbolic Seige of Jerusalem");
                map.Add("26.6", "4-7. Symbolic Seige of Jerusalem");
                map.Add("26.7", "4-7. Symbolic Seige of Jerusalem");
                map.Add("26.8", "8-11. Ezekiel's Vision'Journey to Jerusalem");
                map.Add("26.9", "8-11. Ezekiel's Vision'Journey to Jerusalem");
                map.Add("26.10", "8-11. Ezekiel's Vision'Journey to Jerusalem");
                map.Add("26.11", "8-11. Ezekiel's Vision'Journey to Jerusalem");
                map.Add("26.12", "12. Ezekiel Moves in his Household Goods");
                map.Add("26.13", "13. False Prophets");
                map.Add("26.14", "14. Hypocritical Inquirers");
                map.Add("26.15", "15. Parable of the Vine Tree");
                map.Add("26.16", "16. Allegory of the Unfaithful Wife");
                map.Add("26.17", "17. Parable of the Two Eagles");
                map.Add("26.18", "18. 'The Soul That Sins, It Shall Die'");
                map.Add("26.19", "19. The Concluding Lamentation");
                map.Add("26.20", "20. The Filth of Idolatry");
                map.Add("26.21", "21. The Song of the Sword");
                map.Add("26.22", "22. The Sins of Jerusalem");
                map.Add("26.23", "23. Oholah and Oholibah");
                map.Add("26.24", "24. The Boiling Pot");
                map.Add("26.25", "25. Ammon, Moab, Edom, Philistia");
                map.Add("26.26", "26-28. Tyre and Sidon");
                map.Add("26.27", "26-28. Tyre and Sidon");
                map.Add("26.28", "26-28. Tyre and Sidon");
                map.Add("26.29", "29-32. Egypt (Six Visions)");
                map.Add("26.30", "29-32. Egypt (Six Visions)");
                map.Add("26.31", "29-32. Egypt (Six Visions)");
                map.Add("26.32", "29-32. Egypt (Six Visions)");
                map.Add("26.33", "33. The Watchman");
                map.Add("26.34", "34. The Shepherds");
                map.Add("26.35", "35. Doom of Edom Confirmed");
                map.Add("26.36", "36. New Covenant Confirmed");
                map.Add("26.37", "37. The Valley of Dry Bones");
                map.Add("26.38", "38-39.Gog and Magog");
                map.Add("26.39", "38-39.Gog and Magog");
                map.Add("26.40", "40-43. The Millennial Temple");
                map.Add("26.41", "40-43. The Millennial Temple");
                map.Add("26.42", "40-43. The Millennial Temple");
                map.Add("26.43", "40-43. The Millennial Temple");
                map.Add("26.44", "44-46. The Millennial Worship");
                map.Add("26.45", "44-46. The Millennial Worship");
                map.Add("26.46", "44-46. The Millennial Worship");
                map.Add("26.47", "47-48. The Millennial Land");
                map.Add("26.48", "47-48. The Millennial Land");

                map.Add("27.1", "1. The Wisdom of Daniel");
                map.Add("27.2", "2. The Dream Image");
                map.Add("27.3", "3. The Fiery Furnace");
                map.Add("27.4", "4. The Tree Vision of Nebuchadnezzar");
                map.Add("27.5", "5. Belshazzar and the Handwriting on the Wall");
                map.Add("27.6", "6. Daniel in the Lions Den");
                map.Add("27.7", "7. The Four Beasts Vision");
                map.Add("27.8", "8. The Ram and Goat Vision");
                map.Add("27.9", "9. Daniel's 70 Weeks");
                map.Add("27.10", "10. The Angelic Conflict");
                map.Add("27.11", "11. The Man of Sin");
                map.Add("27.12", "12. The Time of the End");
                map.Add("27.13", "13. Story of Susanna");
                map.Add("27.14", "14. Bel and the Dragon");

                map.Add("28.1", "1-3. Hosea's Wife and Children");
                map.Add("28.2", "1-3. Hosea's Wife and Children");
                map.Add("28.3", "1-3. Hosea's Wife and Children");
                map.Add("28.4", "4. Ephraim is Joined to Idols");
                map.Add("28.5", "5. Ephraim Shall Become a Ruin");
                map.Add("28.6", "6. Priests Murder and Commit Lewdness");
                map.Add("28.7", "7. They Are All Adulterers");
                map.Add("28.8", "8. Have Sown the Wind, Shall Reap the Whirlwind");
                map.Add("28.9", "9. Abominable Like the Idols They Love");
                map.Add("28.10", "10. The Glory of Bethel is Departed");
                map.Add("28.11", "11. How Shall I Give You Up?");
                map.Add("28.12", "12. Jacob Found God at Bethel");
                map.Add("28.13", "13. They Sin More and More");
                map.Add("28.14", "14. Israel Shall Return to God");
                map.Add("29.1", "1. The Plague of Locusts");
                map.Add("29.2", "2. The Coming Day of the Lord");
                map.Add("29.3", "3. Great Events of the Day of the Lord");
                map.Add("30.1", "1-2. Judgments on Surrounding Nations");
                map.Add("30.2", "1-2. Judgments on Surrounding Nations");
                map.Add("30.3", "3. The Luxurious Palaces of Samaria");
                map.Add("30.4", "4. 'Prepare to Meet thy God'");
                map.Add("30.5", "5. The Day of the Lord");
                map.Add("30.6", "6. The Assyrian Captivity");
                map.Add("30.7", "7. Three Visions of Destruction (Locusts, Fire, Plumbline)");
                map.Add("30.8", "8. The Basket of Summer Fruit");
                map.Add("30.9", "9. Future Kingdom Blessing of Restored Israel");
                map.Add("31.1", "1. The Judgment of Edom & Restoration of Israel");
                map.Add("32.1", "1. Jonah's Flight");
                map.Add("32.2", "2. Jonah's Prayer");
                map.Add("32.3", "3. Ninevah's Repentance");
                map.Add("32.4", "4. Jonah's Chagrin");
                map.Add("33.1", "1. Samaria Doomed");
                map.Add("33.2", "2-3. Brutality of the Rulers");
                map.Add("33.3", "2-3. Brutality of the Rulers");
                map.Add("33.4", "4. Prophecy of the Millennial Kingdom");
                map.Add("33.5", "5. Prophecy of Christ's Birth");
                map.Add("33.6", "6. Jehovah's Controversy with His People");
                map.Add("33.7", "7. Desolation, But God Will Triumph");
                map.Add("34.1", "1. Ninevah Will Be Judged");
                map.Add("34.2", "2. The Judgment is Executed");
                map.Add("34.3", "3. Further Reasons Why");
                map.Add("35.1", "1-2. The Prophet's Two Dialogues with God");
                map.Add("35.2", "1-2. The Prophet's Two Dialogues with God");
                map.Add("35.3", "3. The Prophet's Prayer and Praise");
                map.Add("36.1", "1. The Judgment of God upon Judah");
                map.Add("36.2", "2. The Judgment of God upon Surrounding Nations");
                map.Add("36.3", "3. Millennial Blessings in Israel");
                map.Add("37.1", "1. Two Messages: Rebuke & Commendation");
                map.Add("37.2", "2. Three Messages: Encouragment, Blessing, & Destruction of Gentile Power");
                map.Add("38.1", "1-6. Eight Night Visions");
                map.Add("38.2", "1-6. Eight Night Visions");
                map.Add("38.3", "1-6. Eight Night Visions");
                map.Add("38.4", "1-6. Eight Night Visions");
                map.Add("38.5", "1-6. Eight Night Visions");
                map.Add("38.6", "1-6. Eight Night Visions");
                map.Add("38.7", "7-8. Question About Fasting");
                map.Add("38.8", "7-8. Question About Fasting");
                map.Add("38.9", "9-11. God's Judgment on Neighbor Nations");
                map.Add("38.10", "9-11. God's Judgment on Neighbor Nations");
                map.Add("38.11", "9-11. God's Judgment on Neighbor Nations");
                map.Add("38.12", "12-14. Second Advent and Acceptance of Messiah as King");
                map.Add("38.13", "12-14. Second Advent and Acceptance of Messiah as King");
                map.Add("38.14", "12-14. Second Advent and Acceptance of Messiah as King");
                map.Add("39.1", "1. Priests'Get Back into Fellowship");
                map.Add("39.2", "2. Priest's and People'Get Back into Fellowship");
                map.Add("39.3", "3. Robbery, but Future Blessing");
                map.Add("39.4", "4. The Second Advent");
                map.Add("40.1", "1-2. The Birth and Reception of the King");
                map.Add("40.2", "1-2. The Birth and Reception of the King");
                map.Add("40.3", "3. The Baptism of the King");
                map.Add("40.4", "4. The Testing of the King");
                map.Add("40.5", "5-7. The Proclamation of the King (Sermon on the Mount)");
                map.Add("40.6", "5-7. The Proclamation of the King (Sermon on the Mount)");
                map.Add("40.7", "5-7. The Proclamation of the King (Sermon on the Mount)");
                map.Add("40.8", "8-10. The Authority of the King");
                map.Add("40.9", "8-10. The Authority of the King");
                map.Add("40.10", "8-10. The Authority of the King");
                map.Add("40.11", "11-12.Opposition to the King");
                map.Add("40.12", "11-12.Opposition to the King");
                map.Add("40.13", "13. The Parables of the King");
                map.Add("40.14", "14-20.The Revelation and Instruction of the King");
                map.Add("40.15", "14-20.The Revelation and Instruction of the King");
                map.Add("40.16", "14-20.The Revelation and Instruction of the King");
                map.Add("40.17", "14-20.The Revelation and Instruction of the King");
                map.Add("40.18", "14-20.The Revelation and Instruction of the King");
                map.Add("40.19", "14-20.The Revelation and Instruction of the King");
                map.Add("40.20", "14-20.The Revelation and Instruction of the King");
                map.Add("40.21", "21-23. The Formal Presentation of the King (Palm Sunday)");
                map.Add("40.22", "21-23. The Formal Presentation of the King (Palm Sunday)");
                map.Add("40.23", "21-23. The Formal Presentation of the King (Palm Sunday)");
                map.Add("40.24", "24-25. The Predictions of the King (Mt. Olivet Discourse)");
                map.Add("40.25", "24-25. The Predictions of the King (Mt. Olivet Discourse)");
                map.Add("40.26", "26-27.The Crucifixion of the King");
                map.Add("40.27", "26-27.The Crucifixion of the King");
                map.Add("40.28", "28. The Resurrection of the King");
                map.Add("41.1", "1. Preparation of the Servant");
                map.Add("41.2", "2-7. Galilean Ministry of the Servant");
                map.Add("41.3", "2-7. Galilean Ministry of the Servant");
                map.Add("41.4", "2-7. Galilean Ministry of the Servant");
                map.Add("41.5", "2-7. Galilean Ministry of the Servant");
                map.Add("41.6", "2-7. Galilean Ministry of the Servant");
                map.Add("41.7", "2-7. Galilean Ministry of the Servant");
                map.Add("41.8", "8-9. NE of Galilee Ministry of the Servant");
                map.Add("41.9", "8-9. NE of Galilee Ministry of the Servant");
                map.Add("41.10", "10. Enroute to Jerusalem Ministry of the Servant");
                map.Add("41.11", "11-13. Jerusalem Ministry of the Servant");
                map.Add("41.12", "11-13. Jerusalem Ministry of the Servant");
                map.Add("41.13", "11-13. Jerusalem Ministry of the Servant");
                map.Add("41.14", "14-15.Crucifixion of the Servant");
                map.Add("41.15", "14-15.Crucifixion of the Servant");
                map.Add("41.16", "16. Resurrection of the Servant");
                map.Add("42.1", "1-4. The Identification of the Son of Man with Men");
                map.Add("42.2", "1-4. The Identification of the Son of Man with Men");
                map.Add("42.3", "1-4. The Identification of the Son of Man with Men");
                map.Add("42.4", "1-4. The Identification of the Son of Man with Men");
                map.Add("42.5", "5-10. The Ministry of the Son of Man to Men");
                map.Add("42.6", "5-10. The Ministry of the Son of Man to Men");
                map.Add("42.7", "5-10. The Ministry of the Son of Man to Men");
                map.Add("42.8", "5-10. The Ministry of the Son of Man to Men");
                map.Add("42.9", "5-10. The Ministry of the Son of Man to Men");
                map.Add("42.10", "5-10. The Ministry of the Son of Man to Men");
                map.Add("42.11", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.12", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.13", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.14", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.15", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.16", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.17", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.18", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.19", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.20", "11-20. The Rejection of the Son of Man by Men");
                map.Add("42.21", "21-23. The Suffering of the Son of Man for Men");
                map.Add("42.22", "21-23. The Suffering of the Son of Man for Men");
                map.Add("42.23", "21-23. The Suffering of the Son of Man for Men");
                map.Add("42.24", "24. The Resurrection of the Son of Man before Men");
                map.Add("43.1", "1. Christ the Word");
                map.Add("43.2", "2. Christ the Creator");
                map.Add("43.3", "3. Christ the Saviour");
                map.Add("43.4", "4. Christ the Water of Life");
                map.Add("43.5", "5. Christ the Judge");
                map.Add("43.6", "6. Christ the Bread of Life");
                map.Add("43.7", "7. Christ the Heavenly One");
                map.Add("43.8", "8-9. Christ the Light of the World");
                map.Add("43.9", "8-9. Christ the Light of the World");
                map.Add("43.10", "10. Christ the Good Shepherd");
                map.Add("43.11", "11. Christ the Resurrection and the Life");
                map.Add("43.12", "12. Christ the Center of Attraction");
                map.Add("43.13", "13. Christ the Advocate");
                map.Add("43.14", "14. Christ the Coming One");
                map.Add("43.15", "15. Christ the Vine");
                map.Add("43.16", "16. Christ the Pre-Eminent One");
                map.Add("43.17", "17. Christ the Intercessor");
                map.Add("43.18", "18-19.Christ the Faithful and Obedient One unto Death");
                map.Add("43.19", "18-19.Christ the Faithful and Obedient One unto Death");
                map.Add("43.20", "20. Christ the Victorious One");
                map.Add("43.21", "21. Christ the Great Shepherd");
                map.Add("44.1", "1. Commission and Ascension");
                map.Add("44.2", "2. Pentecost");
                map.Add("44.3", "3. Lame Man Healed");
                map.Add("44.4", "4. The First Persecution");
                map.Add("44.5", "5. Ananias and Sapphira");
                map.Add("44.6", "6. The First Deacons");
                map.Add("44.7", "7. Stephen and Martyrdom");
                map.Add("44.8", "8. Philip and the Eunuch");
                map.Add("44.9", "9. Saul's Conversion on the Damascus Road");
                map.Add("44.10", "10. Peter and Cornelius");
                map.Add("44.11", "11. Peter Vindicates Ministry to the Gentiles");
                map.Add("44.12", "12. Peter in Prison");
                map.Add("44.13", "13-14. 1st Missionary Journey");
                map.Add("44.14", "13-14. 1st Missionary Journey");
                map.Add("44.15", "15. Jerusalem Council");
                map.Add("44.16", "16-18. 2nd Missionary Journey");
                map.Add("44.17", "16-18. 2nd Missionary Journey");
                map.Add("44.18", "16-18. 2nd Missionary Journey");
                map.Add("44.19", "19-20. 3rd Missionary Journey");
                map.Add("44.20", "19-20. 3rd Missionary Journey");
                map.Add("44.21", "21. Paul Arrives at Jerusalem");
                map.Add("44.22", "22. Paul's Defense Before the Multitudes");
                map.Add("44.23", "23. Defense Before Sanhedrin");
                map.Add("44.24", "24. Before Felix");
                map.Add("44.25", "25. Before Festus");
                map.Add("44.26", "26. Before King Agrippa");
                map.Add("44.27", "27. Shipwreck");
                map.Add("44.28", "28. Rome");
                map.Add("45.1", "1. All Gentiles Under Sin");
                map.Add("45.2", "2. All Jews Under Sin");
                map.Add("45.3", "3. All Have Sinned");
                map.Add("45.4", "4-5. Justification by Faith");
                map.Add("45.5", "4-5. Justification by Faith");
                map.Add("45.6", "6-8. The Christian Walk");
                map.Add("45.7", "6-8. The Christian Walk");
                map.Add("45.8", "6-8. The Christian Walk");
                map.Add("45.9", "9. Israel in Prophecy");
                map.Add("45.10", "10. Israel in Failure");
                map.Add("45.11", "11. Israel in Success");
                map.Add("45.12", "12. Living Sacrifice");
                map.Add("45.13", "13. Love Your Neighbor");
                map.Add("45.14", "14. Discerning the Doubtful");
                map.Add("45.15", "15. Jew & Gentile, One in Christ");
                map.Add("45.16", "16. Paul's Friends");
                map.Add("46.1", "1. Divisions");
                map.Add("46.2", "2. Natural, Carnal, Spiritual Man");
                map.Add("46.3", "3. Judgment Seat of Christ");
                map.Add("46.4", "4. Judging Each Other");
                map.Add("46.5", "5. Immorality Rebuked");
                map.Add("46.6", "6. Lawsuits With Christians");
                map.Add("46.7", "7. Christian Marriage");
                map.Add("46.8", "8. Meats Offered to Idols");
                map.Add("46.9", "9. Castaway Chapter");
                map.Add("46.10", "10. Israel's Bad Example");
                map.Add("46.11", "11. Conduct at the Lord's Supper");
                map.Add("46.12", "12. Spiritual Gifts");
                map.Add("46.13", "13. Love Chapter");
                map.Add("46.14", "14. Spiritual Gifts");
                map.Add("46.15", "15. Resurrection Chapter");
                map.Add("46.16", "16. Closing Instructions");
                map.Add("47.1", "1. Paul's Plan to Come to Corinth");
                map.Add("47.2", "2. Immoral Man Cleansed");
                map.Add("47.3", "3. The Glorious Ministry");
                map.Add("47.4", "4. The Suffering Ministry");
                map.Add("47.5", "5. The Reconciling Ministry");
                map.Add("47.6", "6. The Separated Ministry");
                map.Add("47.7", "7. The Heart of Paul");
                map.Add("47.8", "8. Money Matters");
                map.Add("47.9", "9. Cheerful Giving");
                map.Add("47.10", "10. Divine Viewpoint vs. Human Viewpoint");
                map.Add("47.11", "11. The Boasting of Paul");
                map.Add("47.12", "12. The Third Heaven and the Thorn");
                map.Add("47.13", "13. Concluding Remarks");
                map.Add("48.1", "1. Gospel Perversion by False Teachers");
                map.Add("48.2", "2. Legalism vs. Grace");
                map.Add("48.3", "3. Abrahamic Covenant");
                map.Add("48.4", "4. The Curse of Legalism");
                map.Add("48.5", "5. Walk in the Spirit, Fruit of the Spirit (inward)");
                map.Add("48.6", "6. Walk in the Spirit, Ministry to Others (outward)");
                map.Add("49.1", "1-2. The Doctrinal Wealth of the Christian");
                map.Add("49.2", "1-2. The Doctrinal Wealth of the Christian");
                map.Add("49.3", "3-4. The Walk of the Christian");
                map.Add("49.4", "3-4. The Walk of the Christian");
                map.Add("49.5", "5-6. The Warfare of the Christian");
                map.Add("49.6", "5-6. The Warfare of the Christian");
                map.Add("50.1", "1. The Mind of Paul");
                map.Add("50.2", "2. The Mind of Christ");
                map.Add("50.3", "3. That I May Know Him");
                map.Add("50.4", "4. What Believers Should Think");
                map.Add("51.1", "1. 7 Superiorities of Christ");
                map.Add("51.2", "2. God is Complete");
                map.Add("51.3", "3. Fruit of Union With Christ");
                map.Add("51.4", "4. Godly Examples'Tychicus, Onesimus, Epaphras");
                map.Add("52.1", "1. Work of Faith, Labor of Love, Steadfastness of Hope");
                map.Add("52.2", "2. Testimony of Paul");
                map.Add("52.3", "3. Timothy's Report to Paul");
                map.Add("52.4", "4. Rapture Chapter");
                map.Add("52.5", "5. Peace and Safety'Then Sudden Destruction");
                map.Add("53.1", "1. Comfort in Persecution");
                map.Add("53.2", "2. The Man of Sin Revealed");
                map.Add("53.3", "3. Disorderly Christians and Busybodies");
                map.Add("54.1", "1. Legalism & Unsound Teaching Rebuked");
                map.Add("54.2", "2. Prayer for Government Leaders");
                map.Add("54.3", "3. Qualifications for Pastors & Deacons");
                map.Add("54.4", "4. Doctrine of Demons vs. Good Doctrine");
                map.Add("54.5", "5. The Ministry of Widows");
                map.Add("54.6", "6. The Christian in Business");
                map.Add("55.1", "1. Lois, Eunice, Timothy");
                map.Add("55.2", "2. A Good Soldier Studies");
                map.Add("55.3", "3. Verbal Inspiration Chapter");
                map.Add("55.4", "4. Paul's Thinking Two Months Before Death");
                map.Add("56.1", "1. Crete & Christianity");
                map.Add("56.2", "2. Looking for that Blessed Hope");
                map.Add("56.3", "3. Production of Divine Good");
                map.Add("56.4", "4. Rejection of Heretics");
                map.Add("57.1", "1. Effectual, Profitable Christianity");
                map.Add("58.1", "1. Angelic Conflict: Christ is Better than the Angels");
                map.Add("58.2", "2. Angelic Conflict: Christ Made Lower than the Angels");
                map.Add("58.3", "3. Christ is Better than Moses");
                map.Add("58.4", "4. The Faith-Rest Technique");
                map.Add("58.5", "5. Christ Our High Priest");
                map.Add("58.6", "6. On to Maturity");
                map.Add("58.7", "7. Melchizedek vs. Aaronic Priesthood");
                map.Add("58.8", "8. New Covenant vs. Mosaic Covenant");
                map.Add("58.9", "9. The Blood of Christ");
                map.Add("58.10", "10. In the Holiest");
                map.Add("58.11", "11. The Hall of Faith");
                map.Add("58.12", "12. Chastisement Chapter");
                map.Add("58.13", "13. Bearing His Reproach");
                map.Add("59.1", "1. Ask For Wisdom Chapter");
                map.Add("59.2", "2. Relationship of Faith and Works");
                map.Add("59.3", "3. Tongue Chapter");
                map.Add("59.4", "4. The Rebuke of Worldliness");
                map.Add("59.5", "5. Practical Pointers on Riches, Patience, & Prayer");
                map.Add("60.1", "1. The Trial of Your Faith is Precious");
                map.Add("60.2", "2. Suffering in the Light of His Suffering");
                map.Add("60.3", "3. How to Win a Negative Husband");
                map.Add("60.4", "4. Strange Trials and Suffering");
                map.Add("60.5", "5. Christian Service'Leaders and People");
                map.Add("61.1", "1. The Great and Precious Promises");
                map.Add("61.2", "2. False Teachers");
                map.Add("61.3", "3. Burning of the Present Heavens and Earth");
                map.Add("62.1", "1-2. Christ is Light");
                map.Add("62.2", "1-2. Christ is Light");
                map.Add("62.3", "3-4. Christ is Love");
                map.Add("62.4", "3-4. Christ is Love");
                map.Add("62.5", "5. Christ is Life");
                map.Add("63.1", "1. Truth vs. Error");
                map.Add("64.1", "1. Hospitality");
                map.Add("65.1", "1. Contending for the Faith");
                map.Add("66.1", "1. Introduction");
                map.Add("66.2", "2-3. The Seven Churches");
                map.Add("66.3", "2-3. The Seven Churches");
                map.Add("66.4", "4. The Heavens Opened");
                map.Add("66.5", "5. The Seven Seals");
                map.Add("66.6", "6. The Seven Seals Opened");
                map.Add("66.7", "7. Sealing of the 144,000");
                map.Add("66.8", "8. The Seven Trumpets");
                map.Add("66.9", "9. The Trumpets Opened");
                map.Add("66.10", "10. The Mighty Angel and the Little Book");
                map.Add("66.11", "11. The Two Witnesses");
                map.Add("66.12", "12. The Seven Personages");
                map.Add("66.13", "13. The Sea Beast and the Earth Beast");
                map.Add("66.14", "14. Vision of the Lamb & the 144,000");
                map.Add("66.15", "15. The Seven Vials");
                map.Add("66.16", "16. The Vials Opened");
                map.Add("66.17", "17. Religious Babylon");
                map.Add("66.18", "18. Commercial Babylon");
                map.Add("66.19", "19. The Second Advent");
                map.Add("66.20", "20. The Great White Throne");
                map.Add("66.21", "21. The New Heavens, New Earth, & New Jerusalem");
                map.Add("66.22", "22. Eternity");

                // Apocrypha

                // Judith
                map.Add("67.1", "1. Nebuchadnezzar's War against Arphaxad");
                map.Add("67.2", "2. Holofernes and Nebuchadnezzar's Revenge");
                map.Add("67.3", "3. Devastation of Nations");
                map.Add("67.4", "4. Eliachim Prays and Prepares for War");
                map.Add("67.5", "5. Holofernes and Achior");
                map.Add("67.6", "6. Holofernes Delivers Achior to Bethulia");
                map.Add("67.7", "7. Holofernes Wages War against Bethulia");
                map.Add("67.8", "8. Judith and Her Plan to save Israel");
                map.Add("67.9", "9. Judith and Her Plan to save Israel");
                map.Add("67.10", "10. Judith Bewitches Holofernes with her Beauty and Charm");
                map.Add("67.11", "11. Judith gains Holofernes's Confidence");
                map.Add("67.12", "12. Holofernes's Banquet and Proposition");
                map.Add("67.13", "13. Judith Returns to Bethulia with Holofernes's Head");
                map.Add("67.14", "14. Judith Rallies Bethulia and Holofernes's body is found");
                map.Add("67.15", "15. The Assyrians Panic and Flee");
                map.Add("67.16", "16. Israel Celebrates Judith and Peace");

                // Wisdom
                map.Add("68.1", "1. The Righteous Path Leads to Wisdom");
                map.Add("68.2", "2. Unrighteous Thinking");
                map.Add("68.3", "3. Suffering");
                map.Add("68.4", "4. Dying");
                map.Add("68.5", "5. Judgeing the Wicked");
                map.Add("68.6", "6. Seeking Wisdom");
                map.Add("68.7", "7. Soloman Finds and Teaches Wisdom");
                map.Add("68.8", "8. Blessings That Come from Wisdom");
                map.Add("68.9", "9. Solomons's Prayer");
                map.Add("68.10", "10. Wisdom Preserves the Righteous");
                map.Add("68.11", "11. The Wisdom of Isreal");
                map.Add("68.12", "12. The Mercy of God");
                map.Add("68.13", "13. False Gods and Idolitry");
                map.Add("68.14", "14. False Gods and Idolitry");
                map.Add("68.15", "15. False Gods and Idolitry");
                map.Add("68.16", "16. History's Examples");
                map.Add("68.17", "17. Egypt's Plague of Darkness");
                map.Add("68.18", "18. Death of the First-Born Plague");
                map.Add("68.19", "19. The Parting of the Red Sea and Final Plagues");

                // Tobit
                map.Add("69.1", "1. Tobit, his Vurture and Courage");
                map.Add("69.2", "2. Tobit Defends his Faith");
                map.Add("69.3", "3. Tobit's and Sarah's Prayers for Death are Ansered");
                map.Add("69.4", "4. Tobit Teaches His Son");
                map.Add("69.5", "5. The Angel Raphael");
                map.Add("69.6", "6. Raphael Advised Tobias about Sarah's Curse");
                map.Add("69.7", "7. The Marriage of Sarah and Tobias");
                map.Add("69.8", "8. Sarah's Cure and the Two Week Wedding Feast");
                map.Add("69.9", "9. Money Received");
                map.Add("69.10", "10. Worry and Delay in Return");
                map.Add("69.11", "11. The Return Home and Restoration of Sight");
                map.Add("69.12", "12. The Guide's Payment and Angelic Revelation");
                map.Add("69.13", "13. Tobit's Joyful Prais");
                map.Add("69.14", "14. The End of Tobit, Tobias, and Nineveh");

                // Sirach
                map.Add("70.1", "1. The Dawn of Wisdom");
                map.Add("70.2", "2. The Service and Fear of God");
                map.Add("70.3", "3. Family and the Scrutability of God");
                map.Add("70.4", "4. Treament of the Poor and of Wives");
                map.Add("70.5", "5. Truth and Meekness Teach Wisdom");
                map.Add("70.6", "6. Friends and Fidelity");
                map.Add("70.7", "7. Evil, Chattle, and Responsibility");
                map.Add("70.8", "8. Choosing your Battles and Integrity");
                map.Add("70.9", "9. Prudence with your Wife and Neighbors");
                map.Add("70.10", "10. Judgement, Leadership, and Arrogance");
                map.Add("70.11", "11. Humility, Discipline, and Praise");
                map.Add("70.12", "12. Good Deeds and Wickedness");
                map.Add("70.13", "13. Wealth, Piety, and Poverty");
                map.Add("70.14", "14. Self Contentment, Greed, and Justice");
                map.Add("70.15", "15. The Love of Wisdome and the Fear of God");
                map.Add("70.16", "16. Impiety and Self Discipline");
                map.Add("70.17", "17. Creation and God's Dominion");
                map.Add("70.18", "18. Embracing the Wisdom");
                map.Add("70.19", "19. Decadence and Correction");
                map.Add("70.20", "20. Vices, Violence, and Self Control");
                map.Add("70.21", "21. Sin, Justice, and Pridence in the Fear of God");
                map.Add("70.22", "22. The Doctrine of Wisdom in Behavior");
                map.Add("70.23", "23. Prayer of Wisdom and the Impropriety of Women");
                map.Add("70.24", "24. Truth, the Sweet Reward of Wisdom");
                map.Add("70.25", "25. Faith and Peace with Family and Neighbors");
                map.Add("70.26", "26. The Good Wife");
                map.Add("70.27", "27. Sin and Justice in the Word of God");
                map.Add("70.28", "28. Anger, Vengance, and Faith");
                map.Add("70.29", "29. Lending, Borrowing and Credit");
                map.Add("70.30", "30. Children and Advice");
                map.Add("70.31", "31. Wealth, Greed, Alms, and Moderation");
                map.Add("70.32", "32. Leadership, Counsel, and being Extolled");
                map.Add("70.33", "33. The Law and Treatment of Chattle");
                map.Add("70.34", "34. The Law and Treatment of Chattle continued");
                map.Add("70.35", "35. The Laws and Tribulation");
                map.Add("70.36", "36. God's Grace with Friends and Enemies");
                map.Add("70.37", "37. True Friends, Counsel, and Allegiance");
                map.Add("70.38", "38. Medicines, Work, and Death");
                map.Add("70.39", "39. The Perpetuation of Wisdom");
                map.Add("70.40", "40. Virtue and The Burden of the Sons of Adam");
                map.Add("70.41", "41. Death and Judgement");
                map.Add("70.42", "42. Trusting Wives and Daughters");
                map.Add("70.43", "43. The Great Gifts of God to Man");
                map.Add("70.44", "44. In Praise of the Men of Glory");
                map.Add("70.45", "45. In Praise of the Men of Glory");
                map.Add("70.46", "46. In Praise of the Men of Glory");
                map.Add("70.47", "47. In Praise of the Men of Glory");
                map.Add("70.48", "48. In Praise of the Men of Glory");
                map.Add("70.49", "49. In Praise of the Men of Glory");
                map.Add("70.50", "50. In Praise of the Men of Glory");
                map.Add("70.51", "51. Praise to God and Wisdom");

                // Baruch
                map.Add("71.1", "1. Setting and Confession");
                map.Add("71.2", "2. Prayer for Mercy");
                map.Add("71.3", "3. In Praise of Wisdom");
                map.Add("71.4", "4. Message for Captives");
                map.Add("71.5", "5. Lamentation and Consolation");
                map.Add("71.6", "6. Jeremiah's Letter");

                // 1 Maccabees
                map.Add("72.1", "1. From Alexander the Great to Antiochus Epiphanes");
                map.Add("72.2", "2. Preparing for Rebellion");
                map.Add("72.3", "3. Mattathias Dies, Judas Leads, Winning Battles");
                map.Add("72.4", "4. The Jewish Temple is Reclaimed, Hanukkah is Born");
                map.Add("72.5", "5. Victory for the Faithful under Judas");
                map.Add("72.6", "6. Judas Attacks the Citadel and Antiochus Dies");
                map.Add("72.7", "7. Campaign of Nicanor crushed by Judas");
                map.Add("72.8", "8. Roman Treaty and defense accord");
                map.Add("72.9", "9. Judas Looses to Bacchides, Peace follows the rise of Jonathan");
                map.Add("72.10", "10. Jonathan the Diplomat means Victory for the Jews");
                map.Add("72.11", "11. Jonathans Pact with Demetrius");
                map.Add("72.12", "12. Jonathan trusts Rome leading to his Capture by Trypho");
                map.Add("72.13", "13. Simon Leads, taking the Citadel After Jonathan Killed");
                map.Add("72.14", "14. Simon Improves ties with Rome and Sparta and Rules Judea");
                map.Add("72.15", "15. Antiochus Helps Simon, Attacks Trypho, turns on Simon");
                map.Add("72.16", "16. Simon's Son succeeds; Dies with 2 Sons by Ptolemy");

                // 2 Maccabees
                map.Add("73.1", "1. Introductory Letter");
                map.Add("73.2", "2. Second Letter ");
                map.Add("73.3", "3. God Protects the Temple from Heliodorus");
                map.Add("73.4", "4. Changing of the High Priests and Onias Murdered");
                map.Add("73.5", "5. Jason Revolts and Antiochus Retaliates");
                map.Add("73.6", "6. Judaism is outlawed and Eleazar becomes a Martyr");
                map.Add("73.7", "7. The Martyrdom of Seven Brothers and Their Mother");
                map.Add("73.8", "8. Judas Enlists 6000 and Defeats Nicanor, Timothy, and Bacchides");
                map.Add("73.9", "9. God punishes Antiochus IV");
                map.Add("73.10", "10. Temple Purified, Antiochus Ascends, Idumeans and Timothy are Defeated");
                map.Add("73.11", "11. Lysias Defeated, Peace Ensues");
                map.Add("73.12", "12. Slaughter at Joppa and Jamnia; Judas Retaliates");
                map.Add("73.13", "13. Menelaus Executed, Treaty with Antiochus After the Battle Near Modin");
                map.Add("73.14", "14. Alcimus denounces Judas; Nicanor Attacks Judas and Razis is a Martyr");
                map.Add("73.15", "15. Judas Defeats Nicanor");

                // Prayer of Azariah  - Additions to Daniel
                map.Add("74.1", "1. Azariah' s prayer for reconciliation");

                // Additions to Esther
                map.Add("75.1", "1. Interpretation of Mordecai’s dream");
                map.Add("75.2", "2. Mordecai's dream of two great dragons");
                map.Add("75.3", "3. Edict of Ahasuerus against the Jews");
                map.Add("75.4", "4. Prayer of Mordecai");
                map.Add("75.5", "5. Prayer of Esther");
                map.Add("75.6", "6. Anger of the king at Esther's intrusion");
                map.Add("75.7", "7. Edict of Ahasuerus in behalf of the Jews");

                // Prayer of Manasseh
                map.Add("76.1", "1. Prayer of Manasseh");

                // 1 Esdras - titles from biblegateway.com (CEB)
                map.Add("80.1", "1. Josiah revives the Passover");
                map.Add("80.2", "2. Exiles return to Jerusalem");
                map.Add("80.3", "3. Contest of the bodyguards");
                map.Add("80.4", "4. Superiority of the king");
                map.Add("80.5", "5. Those returning from captivity");
                map.Add("80.6", "6. Work on the temple is finished");
                map.Add("80.7", "7. Work on the temple is finished");
                map.Add("80.8", "8. Ezra leads more exiles out of Babylon");
                map.Add("80.9", "9. Ezra leads more exiles out of Babylon");

                // 2 Esdras - titles from biblegateway.com (CEB)
                map.Add("81.1", "1. Rejection of Israel as God's people");
                map.Add("81.2", "2. The church as God’s people");
                map.Add("81.3", "3. First dialogue");
                map.Add("81.4", "4. First dialogue");
                map.Add("81.5", "5. First dialogue");
                map.Add("81.6", "6. Second dialogue");
                map.Add("81.7", "7. Second dialogue");
                map.Add("81.8", "8. Second dialogue");
                map.Add("81.9", "9. Vision of the woman in mourning");
                map.Add("81.10", "10. Vision of the woman in mourning");
                map.Add("81.11", "11. Vision of the eagle and the lion");
                map.Add("81.12", "12. Vision of the eagle and the lion");
                map.Add("81.13", "13. Vision of the man from the sea");
                map.Add("81.14", "14. Ezra renews the scriptures");
                map.Add("81.15", "15. A Christian addition");
                map.Add("81.16", "16. Oracles of doom against the nations");

                // Bel and the Dragon
                map.Add("87.1", "1. Bel and the Dragon");
            }
            return (string)map[book.ToString() + "." + chapter.ToString()];
        }
    }
}
