//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Bible_Reader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_Bible_Reader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backward {
            get {
                object obj = ResourceManager.GetObject("backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backward_inv {
            get {
                object obj = ResourceManager.GetObject("backward_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bible {
            get {
                object obj = ResourceManager.GetObject("bible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bible_inv {
            get {
                object obj = ResourceManager.GetObject("bible_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;books&gt;
        ///  &lt;book name=&quot;Genesis&quot;&gt;
        ///    &lt;ccelID&gt;1&lt;/ccelID&gt;
        ///    &lt;osisID&gt;Gen&lt;/osisID&gt;
        ///    &lt;chapters&gt;50&lt;/chapters&gt;
        ///    &lt;version&gt;&lt;/version&gt;
        ///    &lt;abbrev&gt;Genesis&lt;/abbrev&gt;
        ///    &lt;abbrev&gt;Ge&lt;/abbrev&gt;
        ///    &lt;abbrev&gt;Gen&lt;/abbrev&gt;
        ///    &lt;abbrev&gt;Gene&lt;/abbrev&gt;
        ///    &lt;abbrev&gt;Genes&lt;/abbrev&gt;
        ///    &lt;abbrev&gt;Gn&lt;/abbrev&gt;
        ///    &lt;firstChap&gt;1&lt;/firstChap&gt;
        ///    &lt;chapter n=&quot;1&quot; verses=&quot;31&quot;/&gt;
        ///    &lt;chapter n=&quot;2&quot; verses=&quot;25&quot;/&gt;
        ///    &lt;chapter n=&quot;3&quot; verses=&quot;24&quot;/&gt;
        ///    &lt;chapter n=&quot;4&quot; verses=&quot;26&quot;/&gt;
        ///    &lt;chapter n=&quot;5&quot; verses=&quot;32&quot;/&gt;
        ///    &lt;chap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bookid {
            get {
                return ResourceManager.GetString("bookid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap books {
            get {
                object obj = ResourceManager.GetObject("books", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap books_inv {
            get {
                object obj = ResourceManager.GetObject("books_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse_inv {
            get {
                object obj = ResourceManager.GetObject("collapse_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] db_mdb {
            get {
                object obj = ResourceManager.GetObject("db_mdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_inv {
            get {
                object obj = ResourceManager.GetObject("edit_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old_Testament=Old Testament
        ///New_Testament=New Testament
        ///Apocrypha=Apocrypha
        ///MainPage_ParagraphOne=Thank you for using Simple Bible Reader. This open-source software is aimed to be simple, yet a powerful reader to support all available bible formats. It is developed with an intention of being portable and faster loading, that does not have any dependencies on the user system. It is also developed to bridge the gap between multiple Bible softwares, so that a user can choose his favorite Bible Software and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old_Testament=Antiguo Testamento
        ///New_Testament=Nuevo Testamento
        ///MainPage_ParagraphOne=Gracias por usar Simple Bible Reader. Este programa de código abierto tiene un enfoque simple de usar, pero es un lector poderoso que admite todos los formatos bíblicos disponibles. El programa ha sido desarrollado con la intención que sea portátil y de carga rápida, sin mayor dependencia del sistema del usuario. El software también está orientado a llenar los vacíos existentes entre los múltiples programas de Biblia, de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand_inv {
            get {
                object obj = ResourceManager.GetObject("expand_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_inv {
            get {
                object obj = ResourceManager.GetObject("find_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_inv {
            get {
                object obj = ResourceManager.GetObject("font_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward {
            get {
                object obj = ResourceManager.GetObject("forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_inv {
            get {
                object obj = ResourceManager.GetObject("forward_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fullscreen {
            get {
                object obj = ResourceManager.GetObject("fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fullscreen_inv {
            get {
                object obj = ResourceManager.GetObject("fullscreen_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gobible {
            get {
                object obj = ResourceManager.GetObject("gobible", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XMLBOOK&gt;
        ///	&lt;NOTES title=&quot;Prologue: The Word Became Flesh&quot;&gt;&amp;lt;h1&amp;gt;Prologue: The Word Became Flesh&amp;lt;/h1&amp;gt;
        ///&amp;lt;p&amp;gt;&amp;lt;font color=&amp;quot;#777777&amp;quot;&amp;gt;&amp;lt;font size=&amp;quot;-1&amp;quot;&amp;gt;&amp;lt;sup&amp;gt;1:1&amp;lt;/sup&amp;gt;&amp;lt;/font&amp;gt;&amp;lt;/font&amp;gt;In the beginning was the Word, and the 
        ///Word was with God, and the Word was God. &amp;lt;font color=&amp;quot;#777777&amp;quot;&amp;gt;&amp;lt;font size=&amp;quot;-1&amp;quot;&amp;gt;&amp;lt;sup&amp;gt;1:2&amp;lt;/sup&amp;gt;&amp;lt;/font&amp;gt;&amp;lt;/font&amp;gt;The same was in the beginning with God. 
        ///&amp;lt;font color=&amp;quot;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gospel_of_john {
            get {
                return ResourceManager.GetString("gospel_of_john", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_inv {
            get {
                object obj = ResourceManager.GetObject("help_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logos_document_xml {
            get {
                object obj = ResourceManager.GetObject("logos_document_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logos4_docx {
            get {
                object obj = ResourceManager.GetObject("logos4_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap more {
            get {
                object obj = ResourceManager.GetObject("more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap more_inv {
            get {
                object obj = ResourceManager.GetObject("more_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paragraph {
            get {
                object obj = ResourceManager.GetObject("paragraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paragraph_inv {
            get {
                object obj = ResourceManager.GetObject("paragraph_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_inv {
            get {
                object obj = ResourceManager.GetObject("print_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old_Testament=Antigo Testamento
        ///New_Testament=Novo Testamento
        ///Apocrypha=Deuterocanônicos
        ///MainPage_ParagraphOne=Obrigado por usar o Simple Bible Reader. Este software de código aberto pretende ser um leitor simples, mas poderoso, para suportar todos os formatos de Bíblia disponíveis. Ele é desenvolvido com o intuito de ser portátil e de carregamento mais rápido, que não possui nenhuma dependência do sistema do usuário. Ele também é desenvolvido para preencher a lacuna entre vários softwares bíblicos, para [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run_inv {
            get {
                object obj = ResourceManager.GetObject("run_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array.prototype.indexOf = IndexOf;
        ///
        ///
        ///
        /////Toggles between two classes for an element
        ///
        ///function ToggleClass(element, firstClass, secondClass, event)
        ///
        ///{
        ///
        ///    event.cancelBubble = true;
        ///
        ///    
        ///
        ///    var classes = element.className.split(&quot; &quot;);
        ///
        ///    var firstClassIndex = classes.indexOf(firstClass);
        ///
        ///    var secondClassIndex = classes.indexOf(secondClass);
        ///
        ///    
        ///
        ///    if (firstClassIndex == -1 &amp;&amp; secondClassIndex == -1)
        ///
        ///    {
        ///
        ///        classes[classes.length] = firstClass;
        ///
        ///    }
        ///
        ///    el [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResultTreeJS {
            get {
                return ResourceManager.GetString("SearchResultTreeJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_menu {
            get {
                object obj = ResourceManager.GetObject("show_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_menu_inv {
            get {
                object obj = ResourceManager.GetObject("show_menu_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stat {
            get {
                object obj = ResourceManager.GetObject("stat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stat_inv {
            get {
                object obj = ResourceManager.GetObject("stat_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old_Testament=பழைய ஏற்பாடு
        ///New_Testament=புதிய ஏற்பாடு
        ///MainPage_ParagraphOne=எளிய வேத படிப்பியை உபயோகிப்பதற்கு நன்றி. இந்த திறந்த மூல மென்பொருள் எளிமையாகவும், அதே நேரத்தில், எல்லா வேத கோப்பு வடிவங்களை உள்ளடக்கிய ஒரு சக்திவாய்ந்த படிப்பியாகவும் இருப்பதே இலக்கு. இது எளிதில் தூக்கி செல்லக்கூடியதாகவும், வேகத்தையும் மனதில் கொண்டு உருவாக்கப்பட்டது. பல வேதமென்பொருட்களின் இடையே உள்ள இடைவெளிக்கு பாலமாகவும், விருப்பப்பட்ட வேதமென்பொருளில் விருப்பப்பட்ட வேதமொழிபெயர்ப்பை உபயோகிக்கவும், இந்த மென்பொருள் உருவாக்கப்ப [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transliterate {
            get {
                object obj = ResourceManager.GetObject("transliterate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transliterate_inv {
            get {
                object obj = ResourceManager.GetObject("transliterate_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;bookStmt&gt;
        ///   &lt;bookDecl id=&quot;GEN&quot;&gt;
        ///    &lt;bookAbbreviation&gt;GE&lt;/bookAbbreviation&gt;
        ///    &lt;chapterSpecifier&gt;Chapter&lt;/chapterSpecifier&gt;
        ///    &lt;verseSpecifier&gt;Verse&lt;/verseSpecifier&gt;
        ///    &lt;shortName&gt;Genesis&lt;/shortName&gt;
        ///    &lt;fullName&gt;The First Book of Moses, called Genesis&lt;/fullName&gt;
        ///   &lt;/bookDecl&gt;
        ///   &lt;bookDecl id=&quot;EXO&quot;&gt;
        ///    &lt;bookAbbreviation&gt;EX&lt;/bookAbbreviation&gt;
        ///    &lt;chapterSpecifier&gt;Chapter&lt;/chapterSpecifier&gt;
        ///    &lt;verseSpecifier&gt;Verse&lt;/verseSpecifier&gt;
        ///    &lt;shortName&gt;Exodus&lt;/shortName&gt;
        ///    &lt;fullName&gt;The Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsem_scripture_header {
            get {
                return ResourceManager.GetString("xsem_scripture_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in_inv {
            get {
                object obj = ResourceManager.GetObject("zoom_in_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_out_inv {
            get {
                object obj = ResourceManager.GetObject("zoom_out_inv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
